
version: "3.8"

services:

  mariadb:
    container_name: nc-containers-db-mariadb-test-01
    image: mariadb:10.7.3-focal
    #restar: always
    environment:
      MARIADB_DATABASE: 'nc-containers-db-mariadb-test-01'
      MARIADB_USER: 'newsoftcomputer'
      MARIADB_PASSWORD: 'newsoftcomputer'
      MARIADB_ROOT_PASSWORD: 'newsoftcomputer'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    #volumes:
      #- "./db:/data/db"
      #- my-db:/var/lib/mariadb